exports.seed = function (knex, Promise) {
  return knex('bakeshops').del()
    .then(function () {
      return knex('bakeshops').insert([
        {bakeshop_id: 3301, bakeshop_name: 'Leeds Street Bakery', bakeshop_logo: 'http://www.leedsstbakery.co.nz/assets/img/75121.jpg', bakeshop_img:'http://www.leedsstbakery.co.nz/assets/img/75130.jpg', bakeshop_url: 'http://www.leedsstbakery.co.nz/', bakeshop_address: '6G/14 Hannah Factory Laneway, Te Aro, Wellington 6011', bakeshop_hours: 'Monday-Friday: 7:30am-3:30pm, Saturday: 8am-4pm, Sunday: Closed', bakeshop_info:"Leeds St Bakery began as a part of Ti Kouka Cafe. The reputation of their delicious baked goods spread far and wide, which ultimately lead to the opening of Leeds St Bakery in 2013. Their freshly baked breads are to die for, and that salted caramel cookie will blow your damn mind."},

        {bakeshop_id: 3302, bakeshop_name: 'Louis Sergeant Sweet Couture', bakeshop_logo: 'http://louissergeant.co.nz/wp-content/uploads/2013/10/louis-sergeant-logo-374.png', bakeshop_img:'https://www.wellingtonnz.com/assets/Uploads/images/listings-eatanddrink/_resampled/ScaleWidthWzE2MDBd/903fe9bd29aefe368b9ba3316763f9a2.jpg', bakeshop_url: 'http://louissergeant.co.nz/', bakeshop_address: '146 Featherston St Wellington New Zealand', bakeshop_hours: 'Monday-Friday: 9am-5pm, Saturday-Sunday: 9am-5:30pm', bakeshop_info: "The incredible and innovative French-inspired desserts crafted by Louis Sergeant's pastry chefs are beyond compare. From the light and delicate macarons and cream puffs, to the divinely rich L'intense Chocolate Cake, you'll need to prepare your tastebuds for this experience. Are you even WORTHY of the glory?!" },

        {bakeshop_id: 3303, bakeshop_name: 'AroBake', bakeshop_logo: 'http://www.arobake.co.nz/site/arobake/images/basic_theme/a2.jpg', bakeshop_img:'https://scontent-syd2-1.xx.fbcdn.net/v/t1.0-9/431549_267377553337881_627237390_n.jpg?oh=9bb518c4a6f57c180321d686698f550c&oe=59D05242', bakeshop_url: 'http://www.arobake.co.nz', bakeshop_address: '6G/14 Hannah Factory Laneway, Te Aro, Wellington 6011', bakeshop_hours: "Monday-Friday: 7am-5:15pm, Saturday: 7am-3:30pm, Sunday: Closed.", bakeshop_info: "The residents of Aro Valley know this bakery well. The entrancing scent of baking bread floats down Aro Street and beyond nearly every morning. It draws you in... it hypnotizes you... resistence is futile."},

        {bakeshop_id: 3304, bakeshop_name: 'Dough Momma', bakeshop_logo: 'http://doughmomma.com/img/dough-momma-logo-1468205300.jpg', bakeshop_img:'http://doughmomma.com/7-home_default/bourbon-pecan.jpg', bakeshop_url: 'http://doughmomma.com', bakeshop_address: 'The Internet! Order immediately. Go to http://doughmomma.com', bakeshop_hours: "Contact Dough Momma for delivery details!", bakeshop_info: "If you need some real, American comfort food, you can do no better than Dough Momma. Have you ever even had a real glazed cinnamon-roll? What are you doing with your life? We recommend the maple-coffee glaze. Don't tell anyone you're ordering, they'll just make you share."}
      ]);
    });
};
